// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_librerias_paco.Context;

#nullable disable

namespace api_librerias_paco.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_librerias_paco.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Libros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaPublicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Paginas")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enVenta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("api_librerias_paco.Models.LibrosClientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("Idlibro")
                        .HasColumnType("int");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<string>("NombreLibro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LibroId");

                    b.ToTable("LibrosClientes");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Tiendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("codigopostal")
                        .HasColumnType("int");

                    b.Property<string>("comunidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("libroId")
                        .HasColumnType("int");

                    b.Property<string>("localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("trabajadores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("libroId");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("api_librerias_paco.Models.LibrosClientes", b =>
                {
                    b.HasOne("api_librerias_paco.Models.Clientes", "Cliente")
                        .WithMany("LibrosClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_librerias_paco.Models.Libros", "Libro")
                        .WithMany("LibrosClientes")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Tiendas", b =>
                {
                    b.HasOne("api_librerias_paco.Models.Libros", "Libros")
                        .WithMany("Tiendas")
                        .HasForeignKey("libroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Libros");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Clientes", b =>
                {
                    b.Navigation("LibrosClientes");
                });

            modelBuilder.Entity("api_librerias_paco.Models.Libros", b =>
                {
                    b.Navigation("LibrosClientes");

                    b.Navigation("Tiendas");
                });
#pragma warning restore 612, 618
        }
    }
}
